### PR TITLE
Add tr locales

### PR DESCRIPTION
**Pull request by mikropsoft**

### CODE REVIEW

**Comment by SebaUbuntu** [comment]
Hi, we use Crowdin for translations

**Comment by SebaUbuntu** [comment]
https://crowdin.com/project/athena-android

**Comment by mikropsoft** [comment]
> https://crowdin.com/project/athena-android

The project appears to be suspended

**Comment by SebaUbuntu** [comment]
Not for me, try to contact Crowdin support

**Comment by mikropsoft** [comment]
> > https://crowdin.com/project/athena-android
> 
> The project appears to be suspended @SebaUbuntu

**Comment by mikropsoft** [comment]
> Not for me, try to contact Crowdin support

So there's nothing wrong with the project?

**Comment by mikropsoft** [comment]
> > > Not for me, try to contact Crowdin support
> > 
> > 
> > So there's nothing wrong with the project?
> 
> Nothing on my end, I can open it just fine

but it seems that no one has supported you for 20 days. I guess you are the project owner so you don't seem to have a problem. can you also create a user account and try?

**Comment by SebaUbuntu** [comment]
> I can also open it with incognito mode w/o being logged in

**Comment by mikropsoft** [comment]
> > I can also open it with incognito mode w/o being logged in

Still, isn't it strange that there hasn't been any support for 20 days? anyway you know :)

**Comment by SebaUbuntu** [comment]
> > > I can also open it with incognito mode w/o being logged in
> 
> Still, isn't it strange that there hasn't been any support for 20 days? anyway you know :)

Confirmed with another user that it still works

**Comment by SebaUbuntu** [comment]
Hi, can you retry now please?

**Comment by mikropsoft** [comment]
> Hi, can you retry now please?

Yes working, I wonder where the problem originated :)

**Pull request closed without merging**
